# Generated by Django 3.0.6 on 2020-05-17 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
