# Generated by Django 3.0.6 on 2020-06-10 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CImage',
            new_name='CImages',
        ),
    ]
