# Generated by Django 3.0.6 on 2020-06-10 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200610_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='image',
            field=models.ImageField(default='aa.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
